name: TSRoots Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.8, 3.9]  # Test across different Python versions

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest coverage pytest-cov  # Install testing dependencies
          pip install -e .[test,docs]  # Install test and docs optional dependencies

      - name: Install optional dependencies (PyTorch and Chebpy)
        run: |
          pip install torch  # Install PyTorch
          pip install git+https://github.com/chebpy/chebpy.git  # Install Chebpy from git

      - name: Run tests with coverage
        run: |
          pytest --cov=src/tsroots --cov-report=term-missing
